"""initial schema

Revision ID: 0001
Revises:

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setting',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.String(length=2000), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('cb_blacklist',
    sa.Column('bond_id', sa.String(length=16), nullable=False, comment='转债代码'),
    sa.Column('bond_nm', sa.String(length=64), nullable=True, comment='转债名称(拉黑时快照)'),
    sa.Column('reason', sa.String(length=200), nullable=True, comment='拉黑原因(可空)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='拉黑时间'),
    sa.PrimaryKeyConstraint('bond_id')
    )
    op.create_table('cb_daily_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='落库时间'),
    sa.Column('bond_id', sa.String(length=16), nullable=False, comment='转债代码'),
    sa.Column('bond_nm', sa.String(length=64), nullable=True, comment='转债名称'),
    sa.Column('stock_id', sa.String(length=16), nullable=True, comment='正股代码'),
    sa.Column('stock_nm', sa.String(length=64), nullable=True, comment='正股名称'),
    sa.Column('price', sa.Float(), nullable=True, comment='转债价格'),
    sa.Column('sprice', sa.Float(), nullable=True, comment='正股价格'),
    sa.Column('increase_rt', sa.Float(), nullable=True, comment='转债涨跌幅(%)'),
    sa.Column('sincrease_rt', sa.Float(), nullable=True, comment='正股涨跌幅(%)'),
    sa.Column('convert_price', sa.Float(), nullable=True, comment='转股价'),
    sa.Column('convert_value', sa.Float(), nullable=True, comment='转股价值'),
    sa.Column('premium_rt', sa.Float(), nullable=True, comment='溢价率(%)'),
    sa.Column('dblow', sa.Float(), nullable=True, comment='双低值'),
    sa.Column('curr_iss_amt', sa.Float(), nullable=True, comment='剩余规模(亿)'),
    sa.Column('orig_iss_amt', sa.Float(), nullable=True, comment='原始规模(亿)'),
    sa.Column('year_left', sa.Float(), nullable=True, comment='剩余年限'),
    sa.Column('maturity_dt', sa.String(length=32), nullable=True, comment='到期日'),
    sa.Column('list_dt', sa.String(length=32), nullable=True, comment='上市日'),
    sa.Column('rating_cd', sa.String(length=16), nullable=True, comment='评级'),
    sa.Column('ytm_rt', sa.Float(), nullable=True, comment='到期税前收益率(%)'),
    sa.Column('put_ytm_rt', sa.Float(), nullable=True, comment='回售收益率(%)'),
    sa.Column('pb', sa.Float(), nullable=True, comment='正股PB'),
    sa.Column('turnover_rt', sa.Float(), nullable=True, comment='换手率(%)'),
    sa.Column('volume', sa.Float(), nullable=True, comment='成交量'),
    sa.Column('svolume', sa.Float(), nullable=True, comment='正股成交量'),
    sa.Column('force_redeem_price', sa.Float(), nullable=True, comment='强赎触发价'),
    sa.Column('put_convert_price', sa.Float(), nullable=True, comment='回售触发价'),
    sa.Column('convert_amt_ratio', sa.Float(), nullable=True, comment='转股比例(%)'),
    sa.Column('market_cd', sa.String(length=16), nullable=True, comment='市场代码'),
    sa.Column('sw_cd', sa.String(length=16), nullable=True, comment='申万行业代码'),
    sa.Column('btype', sa.String(length=8), nullable=True, comment='债券类型'),
    sa.Column('raw_json', sa.String(), nullable=True, comment='原始 cell JSON'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bond_id', 'trade_date', name='uq_cb_snapshot_bond_date')
    )
    with op.batch_alter_table('cb_daily_snapshot', schema=None) as batch_op:
        batch_op.create_index('ix_cb_snapshot_bond', ['bond_id'], unique=False)
        batch_op.create_index('ix_cb_snapshot_date', ['trade_date'], unique=False)

    op.create_table('cb_index_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='落库时间'),
    sa.Column('index_value', sa.Float(), nullable=True, comment='等权指数值'),
    sa.Column('median_price', sa.Float(), nullable=True, comment='价格中位数'),
    sa.Column('avg_price', sa.Float(), nullable=True, comment='平均价格'),
    sa.Column('avg_ytm', sa.Float(), nullable=True, comment='平均到期收益率(%)'),
    sa.Column('median_convert_value', sa.Float(), nullable=True, comment='中位数转股价值'),
    sa.Column('avg_dblow', sa.Float(), nullable=True, comment='平均双低'),
    sa.Column('avg_premium', sa.Float(), nullable=True, comment='平均溢价率(%)'),
    sa.Column('median_premium', sa.Float(), nullable=True, comment='中位数溢价率(%)'),
    sa.Column('turnover_rate', sa.Float(), nullable=True, comment='换手率(%)'),
    sa.Column('count', sa.Float(), nullable=True, comment='转债数量'),
    sa.Column('temperature', sa.Float(), nullable=True, comment='温度'),
    sa.Column('idx_price', sa.Float(), nullable=True, comment='指数价格'),
    sa.Column('idx_increase_rt', sa.Float(), nullable=True, comment='指数涨幅(%)'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', name='uq_cb_index_date')
    )
    with op.batch_alter_table('cb_index_daily', schema=None) as batch_op:
        batch_op.create_index('ix_cb_index_date', ['trade_date'], unique=False)

    op.create_table('cb_redeem_daily',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='落库时间'),
    sa.Column('bond_id', sa.String(length=16), nullable=False, comment='转债代码'),
    sa.Column('bond_nm', sa.String(length=64), nullable=True, comment='转债名称'),
    sa.Column('stock_id', sa.String(length=16), nullable=True, comment='正股代码'),
    sa.Column('stock_nm', sa.String(length=64), nullable=True, comment='正股名称'),
    sa.Column('redeem_icon', sa.String(length=8), nullable=True, comment='强赎标记(R/O/B/G)'),
    sa.Column('redeem_flag', sa.String(length=8), nullable=True, comment='强赎公告标志'),
    sa.Column('redeem_remain_days', sa.Integer(), nullable=True, comment='临近强赎触发剩余天数'),
    sa.Column('redeem_real_days', sa.Integer(), nullable=True, comment='已满足天数'),
    sa.Column('redeem_count_days', sa.Integer(), nullable=True, comment='需满足天数'),
    sa.Column('redeem_total_days', sa.Integer(), nullable=True, comment='统计总天数'),
    sa.Column('redeem_price', sa.Float(), nullable=True, comment='赎回价'),
    sa.Column('redeem_price_ratio', sa.String(length=16), nullable=True, comment='赎回价比例'),
    sa.Column('force_redeem_price', sa.Float(), nullable=True, comment='强赎触发价'),
    sa.Column('redeem_dt', sa.String(length=32), nullable=True, comment='赎回日'),
    sa.Column('recount_dt', sa.String(length=32), nullable=True, comment='重新计数日'),
    sa.Column('delist_dt', sa.String(length=32), nullable=True, comment='退市日'),
    sa.Column('force_redeem', sa.String(), nullable=True, comment='强赎公告文字'),
    sa.Column('raw_json', sa.String(), nullable=True, comment='原始 cell JSON'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bond_id', 'trade_date', name='uq_cb_redeem_bond_date')
    )
    with op.batch_alter_table('cb_redeem_daily', schema=None) as batch_op:
        batch_op.create_index('ix_cb_redeem_bond', ['bond_id'], unique=False)
        batch_op.create_index('ix_cb_redeem_date', ['trade_date'], unique=False)

    op.create_table('cn_bond_yield',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日'),
    sa.Column('yield_2y', sa.Float(), nullable=True, comment='2年期(%)'),
    sa.Column('yield_5y', sa.Float(), nullable=True, comment='5年期(%)'),
    sa.Column('yield_10y', sa.Float(), nullable=True, comment='10年期(%)'),
    sa.Column('yield_30y', sa.Float(), nullable=True, comment='30年期(%)'),
    sa.Column('spread_10y_2y', sa.Float(), nullable=True, comment='10Y-2Y期限利差'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='落库时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trade_date', name='uq_bond_date')
    )
    with op.batch_alter_table('cn_bond_yield', schema=None) as batch_op:
        batch_op.create_index('ix_bond_date', ['trade_date'], unique=False)

    op.create_table('index_daily_quote',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('index_code', sa.String(length=16), nullable=False, comment='指数代码'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='落库时间'),
    sa.Column('open', sa.Float(), nullable=True, comment='开盘价'),
    sa.Column('close', sa.Float(), nullable=True, comment='收盘价'),
    sa.Column('high', sa.Float(), nullable=True, comment='最高价'),
    sa.Column('low', sa.Float(), nullable=True, comment='最低价'),
    sa.Column('volume', sa.Float(), nullable=True, comment='成交量'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_code', 'trade_date', name='uq_quote_idx_date')
    )
    with op.batch_alter_table('index_daily_quote', schema=None) as batch_op:
        batch_op.create_index('ix_quote_idx_date', ['index_code', 'trade_date'], unique=False)

    op.create_table('index_dividend_yield',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('index_code', sa.String(length=16), nullable=False, comment='指数代码'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日'),
    sa.Column('dividend_yield', sa.Float(), nullable=True, comment='股息率(%)'),
    sa.Column('dividend_yield_percentile_1y', sa.Float(), nullable=True),
    sa.Column('dividend_yield_percentile_3y', sa.Float(), nullable=True),
    sa.Column('dividend_yield_percentile_5y', sa.Float(), nullable=True),
    sa.Column('dividend_yield_percentile_10y', sa.Float(), nullable=True),
    sa.Column('dividend_yield_average_5y', sa.Float(), nullable=True, comment='5年均值'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='落库时间'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_code', 'trade_date', name='uq_dividend_idx_date')
    )
    with op.batch_alter_table('index_dividend_yield', schema=None) as batch_op:
        batch_op.create_index('ix_dividend_idx_date', ['index_code', 'trade_date'], unique=False)

    op.create_table('index_valuation_snapshot',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('index_code', sa.String(length=16), nullable=False, comment='指数代码'),
    sa.Column('index_name', sa.String(length=64), nullable=False, comment='指数名称'),
    sa.Column('trade_date', sa.Date(), nullable=False, comment='交易日'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='落库时间'),
    sa.Column('pe', sa.Float(), nullable=True, comment='PE-TTM'),
    sa.Column('pb', sa.Float(), nullable=True, comment='PB'),
    sa.Column('ps', sa.Float(), nullable=True, comment='PS'),
    sa.Column('pe_percentile_3m', sa.Float(), nullable=True),
    sa.Column('pe_percentile_6m', sa.Float(), nullable=True),
    sa.Column('pe_percentile_1y', sa.Float(), nullable=True),
    sa.Column('pe_percentile_2y', sa.Float(), nullable=True),
    sa.Column('pe_percentile_3y', sa.Float(), nullable=True),
    sa.Column('pe_percentile_5y', sa.Float(), nullable=True),
    sa.Column('pe_percentile_10y', sa.Float(), nullable=True),
    sa.Column('pe_percentile_ytd', sa.Float(), nullable=True, comment='今年以来'),
    sa.Column('pe_percentile_bgn', sa.Float(), nullable=True, comment='成立以来'),
    sa.Column('pb_percentile_3m', sa.Float(), nullable=True),
    sa.Column('pb_percentile_6m', sa.Float(), nullable=True),
    sa.Column('pb_percentile_1y', sa.Float(), nullable=True),
    sa.Column('pb_percentile_2y', sa.Float(), nullable=True),
    sa.Column('pb_percentile_3y', sa.Float(), nullable=True),
    sa.Column('pb_percentile_5y', sa.Float(), nullable=True),
    sa.Column('pb_percentile_10y', sa.Float(), nullable=True),
    sa.Column('pb_percentile_ytd', sa.Float(), nullable=True, comment='今年以来'),
    sa.Column('pb_percentile_bgn', sa.Float(), nullable=True, comment='成立以来'),
    sa.Column('ps_percentile_3m', sa.Float(), nullable=True),
    sa.Column('ps_percentile_6m', sa.Float(), nullable=True),
    sa.Column('ps_percentile_1y', sa.Float(), nullable=True),
    sa.Column('ps_percentile_2y', sa.Float(), nullable=True),
    sa.Column('ps_percentile_3y', sa.Float(), nullable=True),
    sa.Column('ps_percentile_5y', sa.Float(), nullable=True),
    sa.Column('ps_percentile_10y', sa.Float(), nullable=True),
    sa.Column('ps_percentile_ytd', sa.Float(), nullable=True, comment='今年以来'),
    sa.Column('ps_percentile_bgn', sa.Float(), nullable=True, comment='成立以来'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_code', 'trade_date', name='uq_valuation_idx_date')
    )
    with op.batch_alter_table('index_valuation_snapshot', schema=None) as batch_op:
        batch_op.create_index('ix_valuation_idx_date', ['index_code', 'trade_date'], unique=False)

    op.create_table('task_run_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False, comment='任务ID,如 valuation_daily'),
    sa.Column('started_at', sa.DateTime(), nullable=False, comment='开始时间(本地)'),
    sa.Column('finished_at', sa.DateTime(), nullable=True, comment='结束时间(本地)'),
    sa.Column('duration_sec', sa.Float(), nullable=True, comment='耗时(秒)'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='success/partial/failed'),
    sa.Column('summary', sa.String(length=2000), nullable=True, comment='运行摘要(摘取日志末尾若干行)'),
    sa.Column('error', sa.String(length=2000), nullable=True, comment='失败时的错误信息'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('task_run_log', schema=None) as batch_op:
        batch_op.create_index('ix_task_run_job_started', ['job_id', 'started_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task_run_log', schema=None) as batch_op:
        batch_op.drop_index('ix_task_run_job_started')

    op.drop_table('task_run_log')
    with op.batch_alter_table('index_valuation_snapshot', schema=None) as batch_op:
        batch_op.drop_index('ix_valuation_idx_date')

    op.drop_table('index_valuation_snapshot')
    with op.batch_alter_table('index_dividend_yield', schema=None) as batch_op:
        batch_op.drop_index('ix_dividend_idx_date')

    op.drop_table('index_dividend_yield')
    with op.batch_alter_table('index_daily_quote', schema=None) as batch_op:
        batch_op.drop_index('ix_quote_idx_date')

    op.drop_table('index_daily_quote')
    with op.batch_alter_table('cn_bond_yield', schema=None) as batch_op:
        batch_op.drop_index('ix_bond_date')

    op.drop_table('cn_bond_yield')
    with op.batch_alter_table('cb_redeem_daily', schema=None) as batch_op:
        batch_op.drop_index('ix_cb_redeem_date')
        batch_op.drop_index('ix_cb_redeem_bond')

    op.drop_table('cb_redeem_daily')
    with op.batch_alter_table('cb_index_daily', schema=None) as batch_op:
        batch_op.drop_index('ix_cb_index_date')

    op.drop_table('cb_index_daily')
    with op.batch_alter_table('cb_daily_snapshot', schema=None) as batch_op:
        batch_op.drop_index('ix_cb_snapshot_date')
        batch_op.drop_index('ix_cb_snapshot_bond')

    op.drop_table('cb_daily_snapshot')
    op.drop_table('cb_blacklist')
    op.drop_table('app_setting')
    # ### end Alembic commands ###
